# This is a basic workflow to help you get started with Actions

name: ADD LABEL

# Controls when the workflow will run
on:
  # Triggers the workflow on close issue
  issues:
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: |
          TAGS="1,2,3"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      
      - name: loop echo
        run: |
          echo 'xxx'
          tags: ${{ steps.prep.outputs.tags }}
      
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.ACTION_SECRET }}
          issue-number: 1
          labels: 'bug'
      
      #- name: Issue Add Projects
       # if: contains(github.event.issue.labels.*.name, 'kind/bug') 
        #uses: actions/add-to-project@v0.3.0
        #with:
         # project-url: https://github.com/users/tianyahui-python/projects/2
          #github-token: ${{ secrets.ACTION_SECRET }}
          #labeled: kind/bug
          #label-operator: OR
          
#       - name: Issue Add  Milestone
#         if: contains(github.event.issue.labels.*.name, 'kind/bug') 
#         uses: cgetc/automatically-set-milestone-to-issue@v0.1.2
#         with:
#           github-token: ${{ secrets.ACTION_SECRET }}
#           version-prefix: "0.1"

            
