# This is a basic workflow to help you get started with Actions

name: ADD LABEL

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare_job:
    name: prepare job
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        id: prep
        run: |
          TAGS="1"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      
  
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        issue_num: [1,2]
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.ACTION_SECRET }}
          issue-number: ${{ matrix.issue_num }}
          labels: 'bug'
      
      #- name: Issue Add Projects
       # if: contains(github.event.issue.labels.*.name, 'kind/bug') 
        #uses: actions/add-to-project@v0.3.0
        #with:
         # project-url: https://github.com/users/tianyahui-python/projects/2
          #github-token: ${{ secrets.ACTION_SECRET }}
          #labeled: kind/bug
          #label-operator: OR
          
#       - name: Issue Add  Milestone
#         if: contains(github.event.issue.labels.*.name, 'kind/bug') 
#         uses: cgetc/automatically-set-milestone-to-issue@v0.1.2
#         with:
#           github-token: ${{ secrets.ACTION_SECRET }}
#           version-prefix: "0.1"

            
