# This is a basic workflow to help you get started with Actions

name: ADD LABEL

# Controls when the workflow will run
on:
  # Triggers the workflow on close issue
  issues:
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add the project label
        uses: andymckay/labeler@master
        with:
          add-labels: "Project: Test"

            
