# This is a basic workflow to help you get started with Actions

name: ADD LABEL

# Controls when the workflow will run
on:
  # Triggers the workflow on close issue
  issues:
    types:
      - closed
      - open

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-bvt-issue:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3

      - name: Check the code to see if the issue number is removed
        run: |
          echo "ok"

            
