# This is a basic workflow to help you get started with Actions

name: ADD LABEL

# Controls when the workflow will run
on:
  # Triggers the workflow on close issue
  issues:
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/users/tianyahui-python/projects/2
          github-token: ${{ secrets.ACTION_SECRET }}
          labeled: bug, needs-triage
          label-operator: OR
          
      - name: git checkout
        uses: actions/checkout@v3
        
      - name: set milestone
        uses: zoispag/action-assign-milestone@v2
        with:
          repo-token: ${{ secrets.ACTION_SECRET }}
          milestone: 0.1

            
