# This is a basic workflow to help you get started with Actions

name: CHECK CI

# Controls when the workflow will run
on:
  # Triggers the workflow on close issue
  issues:
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-bvt-issue:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      
     
      - name: check the code to see if the issue number is removed
        if: contains(github.event.issue.labels.*.name, 'bug')
        
        run: |       
          echo  "issue#$ISSUE_NUM"
          res=`grep -r "issue#$ISSUE_NUM" ${{ github.workspace }}/test || true`
          
          echo "$res"
          
          if [ -n "$res" ]; then
            echo "::set-output name=check_val::True"
          else
            echo "::set-output name=check_val::False"
          fi
          
        env:
          ISSUE_NUM: ${{ github.event.issue.number }}
            
        
        id: get_check_val
        
      - name: get check val
        run: |
          echo ${{ steps.get_check_val.outputs.check_val }}
          
          
      - name: Reopen Issue
        
        if: ${{ steps.get_check_val.outputs.check_val == 'True' }} 
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'open-issue'
          token: ${{ secrets.ACTION_SECRET }}
          issue-number: ${{ github.event.issue.number }}
        

