# This is a basic workflow to help you get started with Actions

name: CHECK CI

# Controls when the workflow will run
on:
  # Triggers the workflow on close issue
  issues:
    types:
      - closed
      - reopened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-bvt-issue:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      

      - env:
          ISSUE_NUM: ${{ github.event.issue.number }}
      
        run: |
          echo $ISSUE_NUM
    
     
      - name: check the code to see if the issue number is removed
        if: contains(github.event.issue.labels.*.name, 'bug')
        
        run: |
          echo execut grep filter command
          
          grep -r 'issue#$ISSUE_NUM' ${{ github.workspace }}/test
          if [ $? == 1 ]; then
            echo "::set-output name=check_val::False"
          else
            echo "::setoutput name=check_val::True"
          fi
        
        id: get_check_val
          
          
      - name: Reopen Issue
        if: ${{ steps.get_check_val.outputs.check_val }} == 'True'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'open-issue'
          token: ${{ secrets.ACTION_SECRET }}
          issue-number: ${{ github.event.issue.number }}
        

