# This is a basic workflow to help you get started with Actions

name: CHECK CI

# Controls when the workflow will run
on:
  # Triggers the workflow on close issue
  issues:
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-bvt-issue:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      
      - name: get issue status
        run: |
          echo ${{ github.event.issue.status }}
      
     
      - name: check the code to see if the issue number is removed
        if: contains(github.event.issue.labels.*.name, 'bug')
        
        run: |
        
          res=`grep -r "issue#$ISSUE_NUM" ${{ github.workspace }}/test || true`
        
          if [ -n "$res" ]; then
            echo "::set-output name=check_val::True"
          else
            echo "::set-output name=check_val::False"
          fi
          
        env:
          ISSUE_NUM: ${{ github.event.issue.number }}
            
        
        id: get_check_val
          
          
      - name: Reopen Issue
        
        if: ${{ steps.get_check_val.outputs.check_val == 'True' }} 
        
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'open-issue'
          token: ${{ secrets.ACTION_SECRET }}
          issue-number: ${{ github.event.issue.number }}
      
          
      - name: create-comment
      
        if: ${{ steps.get_check_val.outputs.check_val == 'True' }} 
        
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.ACTION_SECRET }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. The bug issue in the BVT test code has not been removed,issues automatically open.

        
