# This is a basic workflow to help you get started with Actions

name: CHECK CI

# Controls when the workflow will run
on:
  # Triggers the workflow on close issue
  issues:
    types:
      - closed
      - reopened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-bvt-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      

      - env:
          ISSUE_NUM: ${{ github.event.issue.number }}
          format_issue: format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat')
        run: |
          echo $ISSUE_NUM
          echo $format_issue

      - name: echo contains true
        if: contains(github.event.issue.labels.*.name, 'bug')
    
        run: grep -r format('{{Hello {0} {1} {2}!}}', 'Mona', 'the', 'Octocat') ${{ github.workspace }}
        
