# This is a basic workflow to help you get started with Actions

name: CHECK CI

# Controls when the workflow will run
on:
  # Triggers the workflow on close issue
  issues:
    types:
      - closed
      - reopened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-bvt-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: echo ls command
        run: |
          ls
          pwd

      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event.issue.labels) }}
          xx: ${{ join(github.event.issue.labels.*.name, ', ')  }}
        run: |
          echo $EVENT_CONTEXT
          echo $xx

      - name: echo contains true
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: grep -r '@bvt:issue#1234' ${{ github.workspace }}
        
        
      - name: if issue label name
        if: github.event.issue
        run: echo if issue label name

      - name: Run a check ci script
        run: |
          echo Hello, world!
      - name: Run a multi-check-ci script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
