# Define workflow name.
name: continuous-regression

on:
  workflow_dispatch:
  

jobs:
  bvt-linux-x86:
    runs-on: 128-tianyahui-repo
    name: BVT Test on Ubuntu/x64
    timeout-minutes: 30
    
    steps:
      - name: checkout head
        uses: actions/checkout@v2
        with:
          path: ./head
          repository: matrixorigin/matrixone
          ref: main
      
#       - name: Set up Go
#         uses: ./head/.github/actions/setup_env

      - name: Set up Go
        run: |
          echo `go version`
        
