# Define workflow name.
name: continuous-regression

on:
  workflow_dispatch:
  

jobs:
  bvt-linux-x86:
    runs-on: 128-runner-label 
    name: BVT Test on Ubuntu/x64
    timeout-minutes: 30
    
    steps:
      - name: checkout head
        uses: actions/checkout@v2
        with:
          path: ./head
          repository: matrixorigin/matrixone
          ref: main

      - name: echo go version
        run: |
          echo `go version`
          
      - name: echo workspace
        run: |
          echo $GITHUB_WORKSPACE
        
      - name: Build MatrixOne
        run: |
          cd $GITHUB_WORKSPACE/head && make clean && make debug
          git rev-parse --short HEAD
          
      - name: Start MO
        run: |
          cd $GITHUB_WORKSPACE/head
          ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml  &>mo-service.log &
          
      - name: Clone mo-tester repository
        uses: actions/checkout@v2
        with:
          repository: matrixorigin/mo-tester
          path: ./mo-tester
          ref: main
          
      #- name: Set up JDK 8 for x64
       # uses: actions/setup-java@v3
        #with:
         # java-version: '8'
          #distribution: 'adopt'
          #architecture: x64
          
      - name: echo java version
        run: |
          echo `java -version`
          
      - name: Start BVT Test
        id: bvt_on_pr_version
        run: |
          export LC_ALL="C.UTF-8"
          locale
          sleep 10s
          cd $GITHUB_WORKSPACE/mo-tester
          ./run.sh -n -g -p $GITHUB_WORKSPACE/head/test/cases 2>&1
          
      - name: Check mo-service Status
        if: ${{ always() && !cancelled() }}
        run: |
          if [ "$(ps -ef | grep 'mo-service' | grep -v "grep" | wc -l)" -gt 0 ]; then pkill -9 mo-service; else echo 'current mo-service has already crashed'; exit 1; fi
          
      - name: remove some files
        continue-on-error: true
        run: |
          cd $GITHUB_WORKSPACE
          if  [ -d  "./head/mo-service"  ]; then rm -rf ./head/mo-service; fi
          rm -rf ./mo-tester/.git
          rm -rf ./mo-tester/lib
          
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        continue-on-error: true
        with:
          name: linux_x86_cd_reports
          path: |
            ${{ github.workspace }}
          retention-days: 7
