# This is a basic workflow to help you get started with Actions

name: Crontab CI

on:
  schedule:
    - cron: '1 * * * *'
    
  workflow_dispatch:
  
jobs:
  check-bvt-code:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
        
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 1
          labels: 'question'
          
      
    
          
     
  
    
