# This is a basic workflow to help you get started with Actions

name: Crontab CI

on:
  # schedule:
   # - cron: '1 * * * *'
    
  workflow_dispatch:
  
jobs:
  get-issue-id:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.get_num.outputs.issue_num }}
    steps:   
      - name: set output num
        id: get_num
        run: |
          echo ::set-output name=issue_num::[1,2,3]
          
      - name: echo num
        run: |
          echo ${{ steps.get_num.outputs.issue_num }}
    

  check-bvt-code:
    runs-on: ubuntu-latest
    needs: get-issue-id
    strategy: 
      matrix:
        version: ${{ needs.get-issue-id.outputs.output1 }}
        
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      
      - name: echo num
        run: |
          echo ${{ matrix.version }}
        
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ matrix.version }}
          labels: 'question'
          
      
    
          
     
  
    
